# Generated by Django 5.0.6 on 2024-05-22 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='appartment_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='address',
            name='building_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='gearbox_type',
            field=models.CharField(choices=[('automatyczna', 'Automatyczna'), ('manualna', 'Manualna'), ('polautomatyczna', 'Polautomatyczna')], max_length=20),
        ),
    ]
